version: '2.1'

services:
  globot:
    image: "globot/bot"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "GloBot:ApiToken=474477823:AAFMWjLjncdWzgTlgHaQs2qY1daz88sAQQg"
      - "GloBot:BotUserName=vstest3e_bot"
      - "GloBot:WebhookUrl=https://6781c77b.ngrok.io/bots/{bot}/webhook/{token}"
      - "token"
      - VIRTUAL_HOST
    ports:
     - 8443
    volumes:
     - "ssl_data:/etc/cert"
  web:
    image: globot/nginx
    build: 
      context: ./nginx/
    ports:
     - "443:443"
    volumes:
     - "ssl_data:/etc/cert"
volumes:
  ssl_data: