version: '2.1'

services:
  globot:
    image: "globot/bot"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "GloBot:ApiToken=474477823:AAFMWjLjncdWzgTlgHaQs2qY1daz88sAQQg"
      - "GloBot:BotUserName=vstest3e_bot"
      - "GloBot:WebhookUrl=https://${VIRTUAL_HOST}/bots/{bot}/webhook/{token}"
      - "GloBot:PathToCertificate=/etc/cert/cert.crt"
      - "VIRTUAL_HOST"
      - "token"
    ports:
     - 8443
    volumes:
     - "ssl_data:/etc/cert"
  web:
    image: globot/nginx
    build: 
      context: ./nginx/
    ports:
     - "443:443"
     - "81:81"
    volumes:
     - "ssl_data:/etc/cert"
    environment:
     - "VIRTUAL_HOST"
volumes:
  ssl_data: