version: '3.4'

services:
  globot:
    image: "nalbandov/globot"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "GloBot:ApiToken=474477823:AAFMWjLjncdWzgTlgHaQs2qY1daz88sAQQg"
      - "GloBot:BotUserName=vstest3e_bot"
      - "GloBot:WebhookUrl=https://6781c77b.ngrok.io/bots/{bot}/webhook/{token}"
      - "token"
    ports:
     - 8443